# Generated by Django 3.2.15 on 2022-09-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_DD',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ME',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_position',
            field=models.TextField(blank=True, choices=[('ME', 'Машинист'), ('DD', 'Дежурный ДЕПО')], max_length=2, null=True),
        ),
    ]
