# Generated by Django 3.2.15 on 2022-09-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_remove_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_DD',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_ME',
        ),
    ]
