# Generated by Django 3.2.11 on 2022-09-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0004_auto_20220917_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_position',
            field=models.TextField(blank=True, choices=[('Машинист', 'Машинист'), ('Дежурный ДЕПО', 'Дежурный ДЕПО')], max_length=30, null=True),
        ),
    ]
