# Generated by Django 3.2.15 on 2022-09-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220917_1520'),
        ('depo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depo',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task', verbose_name='Link to task'),
        ),
    ]
