# Generated by Django 3.2.15 on 2022-09-17 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0002_depo_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepoCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Пункт')),
            ],
        ),
        migrations.RemoveField(
            model_name='depo',
            name='name',
        ),
        migrations.AddField(
            model_name='depo',
            name='depochoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='depo.depocopy'),
        ),
    ]
