# Generated by Django 3.2.15 on 2022-09-17 19:56

from django.db import migrations
import treasuremap.fields


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0005_depo_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depo',
            name='point',
            field=treasuremap.fields.LatLongField(blank=True, max_length=24, null=True),
        ),
    ]
