# Generated by Django 3.2.11 on 2022-09-18 07:21

from django.db import migrations
import treasuremap.fields


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0006_alter_depo_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depo',
            name='point',
        ),
        migrations.AddField(
            model_name='depocopy',
            name='point',
            field=treasuremap.fields.LatLongField(blank=True, max_length=24, null=True),
        ),
    ]
