# Generated by Django 3.2.11 on 2022-09-18 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_arriving_time'),
        ('depo', '0007_auto_20220918_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_eng_get', models.BooleanField(null=True, verbose_name='Приехал')),
                ('machine_eng_pop', models.BooleanField(blank=True, null=True, verbose_name='Выехал')),
                ('depo_eng_get', models.BooleanField(null=True, verbose_name='Приехал')),
                ('depo_eng_pop', models.BooleanField(blank=True, null=True, verbose_name='Выехал')),
                ('depo', models.ForeignKey(max_length=20000, on_delete=django.db.models.deletion.DO_NOTHING, to='depo.depocopy')),
                ('tasks', models.ForeignKey(max_length=20000, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task')),
            ],
        ),
    ]
