# Generated by Django 3.2.11 on 2022-09-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0008_checking'),
    ]

    operations = [
        migrations.AddField(
            model_name='depo',
            name='depo_eng_get',
            field=models.BooleanField(null=True, verbose_name='Приехал'),
        ),
        migrations.AddField(
            model_name='depo',
            name='depo_eng_pop',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выехал'),
        ),
        migrations.AddField(
            model_name='depo',
            name='machine_eng_get',
            field=models.BooleanField(null=True, verbose_name='Приехал'),
        ),
        migrations.AddField(
            model_name='depo',
            name='machine_eng_pop',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выехал'),
        ),
        migrations.DeleteModel(
            name='Checking',
        ),
    ]
