# Generated by Django 3.2.15 on 2022-09-17 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_at', models.DateTimeField(blank=True, null=True, verbose_name='Явка на работу')),
                ('check_med', models.BooleanField(blank=True, null=True, verbose_name='Прошел мед осмотр')),
                ('locomative_start', models.DateField(blank=True, null=True, verbose_name='Прием локоматива начало')),
                ('locomative_end', models.DateField(blank=True, null=True, verbose_name='Прием локоматива конец')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Название задания')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('departer_time', models.DateTimeField(blank=True, null=True, verbose_name='Время выезда ')),
                ('arriving_time', models.DateTimeField(blank=True, null=True, verbose_name='')),
                ('locomative_pass', models.DateField(blank=True, null=True, verbose_name='Сдача локоматива')),
                ('complate_task', models.DateTimeField(blank=True, null=True, verbose_name='Завершение работы')),
                ('user_position', models.ForeignKey(max_length=20000, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
