# Generated by Django 3.2.15 on 2022-09-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='locomative_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Прием локоматива конец'),
        ),
        migrations.AlterField(
            model_name='task',
            name='locomative_pass',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сдача локоматива'),
        ),
        migrations.AlterField(
            model_name='task',
            name='locomative_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Прием локоматива начало'),
        ),
    ]
