# Generated by Django 3.2.11 on 2022-09-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220917_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='arriving_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия'),
        ),
    ]
